# Generated by Django 5.2.14 on 2026-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. Si renseigné, ce nom apparaîtra à la place de votre adresse e-mail dans les boîtes de réception des thérapeutes.",
                max_length=64,
                verbose_name="nom affiché",
            ),
        ),
    ]
