# Generated by Django 5.2.14 on 2026-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="voice_note",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="voice_notes/%Y/%m/",
                verbose_name="note vocale",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, verbose_name="contenu"),
        ),
    ]
