# Generated by Django 5.2.14 on 2026-05-07 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=128, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="nom complet"),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Une phrase qui résume votre approche.",
                        max_length=160,
                        verbose_name="titre court",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="présentation")),
                (
                    "specialties",
                    models.CharField(
                        blank=True,
                        help_text="Séparées par des virgules",
                        max_length=255,
                        verbose_name="spécialités",
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        default="Français",
                        help_text="Séparées par des virgules",
                        max_length=128,
                        verbose_name="langues parlées",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="therapists/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(
                        blank=True,
                        help_text="CCP / RIB / Edahabia ou autres détails. Affiché à l'utilisateur après réservation.",
                        verbose_name="instructions de paiement",
                    ),
                ),
                (
                    "session_price_dzd",
                    models.PositiveIntegerField(
                        default=0, verbose_name="prix de la séance (DZD)"
                    ),
                ),
                (
                    "session_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="durée de la séance (minutes)"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="statut de vérification",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="notes de vérification"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profil thérapeute",
                "verbose_name_plural": "profils thérapeutes",
                "ordering": ("-created_at",),
            },
        ),
    ]
