# Generated by Django 5.2.14 on 2026-05-07 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="jour",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="début")),
                ("end_time", models.TimeField(verbose_name="fin")),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="therapists.therapistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "disponibilité",
                "verbose_name_plural": "disponibilités",
                "ordering": ("weekday", "start_time"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("therapist", "weekday", "start_time"),
                        name="unique_availability_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=128, verbose_name="raison"),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_exceptions",
                        to="therapists.therapistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "exception de disponibilité",
                "verbose_name_plural": "exceptions de disponibilité",
                "ordering": ("date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("therapist", "date"),
                        name="unique_availability_exception",
                    )
                ],
            },
        ),
    ]
