# Generated by Django 5.2.14 on 2026-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0002_availability_availabilityexception"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Femme"),
                    ("male", "Homme"),
                    ("non_binary", "Non binaire"),
                    ("other", "Préfère ne pas préciser"),
                ],
                default="other",
                help_text="Permet aux patient·e·s qui le souhaitent de filtrer par préférence de genre (PRD §8 cultural adaptation).",
                max_length=16,
                verbose_name="genre",
            ),
        ),
    ]
