# Generated by Django 5.2.14 on 2026-05-07 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("therapists", "0002_availability_availabilityexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_start", models.DateTimeField(verbose_name="début")),
                ("slot_end", models.DateTimeField(verbose_name="fin")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_payment", "En attente de paiement"),
                            ("awaiting_confirmation", "Paiement à confirmer"),
                            ("confirmed", "Confirmé"),
                            ("completed", "Terminé"),
                            ("no_show", "Absent"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending_payment",
                        max_length=24,
                        verbose_name="état",
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(blank=True, verbose_name="notes utilisateur"),
                ),
                ("user_marked_paid_at", models.DateTimeField(blank=True, null=True)),
                ("therapist_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/%Y/%m/",
                        verbose_name="justificatif",
                    ),
                ),
                (
                    "daily_room_url",
                    models.URLField(blank=True, verbose_name="lien vidéo"),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="raison d'annulation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="therapists.therapistprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "réservation",
                "verbose_name_plural": "réservations",
                "ordering": ("-slot_start",),
            },
        ),
    ]
