# Generated by Django 5.2.14 on 2026-05-07 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("therapists", "0002_availability_availabilityexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "user"),
                    ("therapist", "therapist"),
                    ("system", "system"),
                ],
                max_length=16,
                verbose_name="annulé·e par",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "pending_payment",
                            "awaiting_confirmation",
                            "confirmed",
                            "completed",
                        ),
                    )
                ),
                fields=("therapist", "slot_start"),
                name="unique_active_booking_slot",
            ),
        ),
    ]
